# Lesson 17: Linear Algebra: scalars, vectors, matrices

## Import libraries

In [1]:
import numpy as np

## Declare variables

In [2]:
s = 5   # Declare a scalar.
s

v = np.array([2, 3, -5])  # Declare a vector.
v
 
m = np.array([[1,3,7], [-2,7,4]])  # Declare a matrix.
m

array([[ 1,  3,  7],
       [-2,  7,  4]])

In [3]:
# "shape" returns the dimension of the object.

m.shape

(2, 3)

In [4]:
v.shape

(3,)

In [5]:
# "reshape" can change the row vecor into the column vector (and columns into rows).

v.reshape(1,3)

array([[ 2,  3, -5]])

In [6]:
v.reshape(3,1)
v

array([ 2,  3, -5])

### Create a tensor

In [7]:
m1 = np.array([[1,2,5], [6,5,4]])
m2 = np.array([[3,2,1],[9,8,7]])

t = np.array([m1,m2])
t

array([[[1, 2, 5],
        [6, 5, 4]],

       [[3, 2, 1],
        [9, 8, 7]]])

### Operations on matrices

In [19]:
v1 = np.array([2,4,-3])
v2 = np.array([5,4,1])

result = np.dot(v1,v2)
result

23

In [20]:
# Subtracting matrices:
m1 - m2

array([[-2,  0,  4],
       [-3, -3, -3]])

In [21]:
# Note that in programming we can add a scalar to a vector or to a matrix (but we cannot add matrices nor
# vectors of different shapes)

m1 + 1

array([[2, 3, 6],
       [7, 6, 5]])

In [22]:
# Transposing of vector and matrices

In [23]:
m1.T   # Transposing matrices

array([[1, 6],
       [2, 5],
       [5, 4]])

In [24]:
v.T  # For vectors it does not work.

array([ 2,  3, -5])

In [25]:
# To transpose vectors we need to first reshape them (redefine their size).
v_reshaped = v.reshape(3,1)
v_reshaped

array([[ 2],
       [ 3],
       [-5]])

In [26]:
v_reshaped.T    # Now it works.

array([[ 2,  3, -5]])

### Dot product

In [27]:
s1 = 9
s2 = 2

res1 = np.dot(s1,s2)
res1

18

In [28]:
v1 = np.array([2,4,-3])
v2 = np.array([5,4,1])

res2 = np.dot(v1,v2)
res2

23

In [30]:
a1 = np.array([[2,1],[3,4]])
a2 = np.array([[7,3],[2,5]])

res3 = np.dot(a1,a2)
res3

array([[16, 11],
       [29, 29]])